name = input("enter your name: ")
number  = int(input("enter a number: "))
print("Your name is %s" % name)
print("Your number + 2 =", number + 2)
print("Your number - 2 =", number - 2)
print("Your number * 2 =", number * 2)
print("Your number / 2 =", number / 2)
print("Your number % 2 =", number % 2)
print("Your number ** 2 =", number ** 2)